version: "3"
services:
  node:
    container_name: node
    image: ghcr.io/gochain/gochain:${GOCHAIN_TAG:-testnet}
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - .:/gochain
    command: gochain --testnet --config /gochain/config.toml --datadir /gochain/node --cache ${GOCHAIN_CACHE:-16000} --rpc --mine --unlock ${GOCHAIN_ACCT} --password /gochain/password.txt --netstats ${NETSTATS_NAME}:${NETSTATS_SECRET}@testnet-stats.gochain.io --miner.extradata ${GOCHAIN_EXTRADATA}
    restart: always
