version: "3"
services:
  node:
    container_name: node
    image: ghcr.io/gochain/gochain:${GOCHAIN_TAG:-latest}
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - .:/gochain
    command: gochain --networkid ${GOCHAIN_NETWORK} --config /gochain/config.toml --nodiscover --datadir /gochain/node --cache ${GOCHAIN_CACHE:-1024} --mine --unlock ${GOCHAIN_ACCT} --password /gochain/password.txt
    restart: always
