version: "3"
services:
  node:
    container_name: node
    image: ghcr.io/gochain/gochain:${GOCHAIN_IMAGE:-latest}
    ports:
      # Netstats
      - "80:80"
      # Proxy
      - "8545:8000"
      # Explorer
      - "8080:8080"
    command: gochain --dev --rpc --metrics --pprof --netstats node:ironsecret@localhost
    restart: always
  netstats:
    container_name: netstats
    image: gcr.io/gochain-core/netstats:${NETSTATS_IMAGE:-latest}
    environment:
      - PORT=80
      - WS_SECRET=ironsecret
      - NETWORK_NAME=localnet
    network_mode: "service:node"
    depends_on:
      - node
    restart: always
  proxy:
    container_name: proxy
    image: gcr.io/gochain-core/rpc-proxy:${RPC_PROXY_IMAGE:-latest}
    depends_on:
      - node
    network_mode: "service:node"
    command: -port 8000 -url http://localhost:8545 -allow "rpc_modules,eth_getCode,clique_getSnapshotAtHash,clique_getSignersAtHash,clique_getVotersAtHash,clique_getSnapshot,clique_getSigners,clique_getVoters,eth_chainId,eth_call,eth_blockNumber,eth_getBalance,eth_sendRawTransaction,eth_gasPrice,eth_estimateGas,net_version,eth_getTransaction,eth_getTransactionReceipt,eth_getTransactionCount,eth_getFilterChanges,net_listening,eth_getBlockByHash,eth_uninstallFilter,eth_getBlockByNumber,eth_newBlockFilter,eth_newPendingTransactionFilter,eth_totalSupply,eth_getLogs,eth_getStorageAt" -rpm 10000
    restart: always
  mongodb:
    container_name: "mongodb"
    image: mongo
    network_mode: "service:node"
    depends_on:
      - node
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    restart: always
  explorer:
    container_name: explorer
    image: gcr.io/gochain-core/explorer:${EXPLORER_IMAGE:-latest}
    network_mode: "service:node"
    depends_on:
      - node
      - mongodb    
    command: "server -d /explorer/ -m localhost:27017 -u http://localhost:8545"
    restart: always
  grabber:
    container_name: grabber
    image: gcr.io/gochain-core/explorer:${EXPLORER_IMAGE:-latest}
    network_mode: "service:node"
    depends_on:
      - node
      - explorer
      - mongodb
    command: "grabber -m localhost:27017 -u http://localhost:8545"
    restart: always
